rackerlabs/docs-cloud-dns

api-docs/common-gs/how-to-use-curl.rst, api-docs/index.rst
Added getting-started to master index.rst page. Fixed malformed hyperlink
=> Fixed small build errors.

script/cibuild
This will get Travis to prepare both subdirectories of docs.
=> Build both api-docs subdirectories

api-docs/v2/getting-started/name-server-setup.rst
=> Updated name server info

api-docs/v2/api-operations/methods/DELETE_deleteRecordset_v2__account_id__zones__zone_id__recordsets__recordset_id__recordsets.rst, api-docs/v2/api-operations/methods/DELETE_deleteZoneExport_v2__account_id__zones_tasks_exports__uuid_id__zones.rst, api-docs/v2/api-operations/methods/DELETE_deleteZoneImport_v2__account_id__zones_tasks_imports__zone_id__zones.rst, api-docs/v2/api-operations/methods/DELETE_deleteZone_v2__account_id__zones__zone_id__zones.rst, api-docs/v2/api-operations/methods/GET_listExportedZone_v2__account_id__zones_tasks_exports__uuid_id__export_zones.rst, api-docs/v2/api-operations/methods/GET_listRecordset_v2__account_id__zones__zone_id__recordsets__recordset_id__recordsets.rst, api-docs/v2/api-operations/methods/GET_listRecordsets_v2__account_id__zones__zone_id__recordsets_recordsets.rst, api-docs/v2/api-operations/methods/GET_listZoneExport_v2__account_id__zones_tasks_exports__uuid_id__zones.rst, api-docs/v2/api-operations/methods/GET_listZoneExports_v2__account_id__zones_tasks_exports_zones.rst, api-docs/v2/api-operations/methods/GET_listZoneImport_v2__account_id__zones_tasks_imports__zone_id__zones.rst, api-docs/v2/api-operations/methods/GET_listZoneImports_v2__account_id__zones_tasks_imports_zones.rst, api-docs/v2/api-operations/methods/GET_listZones_v2__account_id__zones_zones.rst, api-docs/v2/api-operations/methods/PATCH_updateZone_v2__account_id__zones__zone_id__zones.rst, api-docs/v2/api-operations/methods/POST_createRecordset_v2__account_id__zones__zone_id__recordsets_recordsets.rst, api-docs/v2/api-operations/methods/POST_createZone_v2__account_id__zones_zones.rst, api-docs/v2/api-operations/methods/POST_exportZone_v2__account_id__zones__uuid_id__tasks_export_zones.rst, api-docs/v2/api-operations/methods/POST_importZone_v2__account_id__zones_tasks_imports_zones.rst, api-docs/v2/api-operations/methods/PUT_updateRecordset_v2__account_id__zones__zone_id__recordsets__recordset_id__recordsets.rst
=> Add parameters to DNS operations

api-docs/v2/api-operations/methods/GET_listExportedZone_v2__account_id__zones_tasks_exports__uuid_id__export_zones.rst, api-docs/v2/api-operations/methods/GET_listZones_v2__account_id__zones_zones.rst
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
=> final corrections to parameters and tables

api-docs/v2/api-operations/index.rst, api-docs/v2/api-operations/methods/GET_listRateLimits_v2_account_id.rst, api-docs/v2/api-operations/other-operations.rst, api-docs/v2/general-api-info/limits.rst
Closes issue #86 
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
=> Add list rate limit operation.

api-docs/v1/common-gs/how-to-use-curl.rst, api-docs/v2/common-gs/how-to-use-curl.rst
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
closes issue #94
=> fix the using curl section

api-docs/v2/additional-resources.rst, api-docs/v2/common-gs/auth-using-curl.rst, api-docs/v2/general-api-info/role-based-access-control.rst, api-docs/v2/getting-started/authenticate.rst
=> Fix broken link

api-docs/v1/additional-resources.rst
=> updated feedback

api-docs/v2/common-gs/get-credentials.rst
=> Update CCP links

api-docs/v2/common-gs/get-credentials.rst
Reverts rackerlabs/docs-cloud-dns#129
=> Revert "Update CCP links"

api-docs/v1/common-gs/how-to-use-curl.rst, api-docs/v1/general-api-info/role-based-access-control.rst, api-docs/v1/getting-started/authenticate.rst, api-docs/v2/common-gs/how-to-use-curl.rst, api-docs/v2/general-api-info/role-based-access-control.rst, api-docs/v2/getting-started/authenticate.rst
=> Change Cloud Identity to Identity

api-docs/v2/additional-resources.rst
=> Remove defunct feedback.rackspace link

api-docs/v1/common-gs/how-to-use-curl.rst, api-docs/v1/general-api-info/role-based-access-control.rst, api-docs/v1/getting-started/authenticate.rst, api-docs/v2/common-gs/how-to-use-curl.rst, api-docs/v2/general-api-info/role-based-access-control.rst, api-docs/v2/getting-started/authenticate.rst
requested by the Identity dev team
=> Change all occurrences of Rackspace Identity to Identity as

api-docs/v1/additional-resources.rst, api-docs/v1/api-reference/index.rst, api-docs/v2/additional-resources.rst, api-docs/v2/api-reference/index.rst, api-docs/v2/index.rst
=> remove sdk and rack cli refs

api-docs/v1/api-reference/methods/post-create-domain-v1.0-account-domains.rst, api-docs/v1/api-reference/methods/put-update-record-v1.0-account-domains-domainid-records-recordid.rst
=> fix documented types for ttl and priority

api-docs/v1/_templates/footer.html, api-docs/v1/_templates/header.html, api-docs/v2/_templates/footer.html, api-docs/v2/_templates/header.html
=> New Blog Name

api-docs/v1/_templates/footer.html, api-docs/v1/getting-started/send-request-ovw.rst, api-docs/v2/_templates/footer.html, api-docs/v2/getting-started/send-request-ovw.rst
=> Remove SDKs and CLI References

api-docs/v1/_templates/head.html, api-docs/v1/_templates/scripts.html, api-docs/v2/_templates/head.html, api-docs/v2/_templates/scripts.html
=> Remove rack-cli dependency and Update CSS, JS References

api-docs/v1/_templates/footer.html, api-docs/v1/_templates/head.html, api-docs/v1/_templates/header.html, api-docs/v1/_templates/layout.html, api-docs/v2/_templates/footer.html, api-docs/v2/_templates/head.html, api-docs/v2/_templates/header.html, api-docs/v2/_templates/layout.html
=> Metadata for Algolia Search
